"""add cafe_time_available to menus table

Revision ID: 2c841cded694
Revises: 7f7814b8ad67
Create Date: 2025-08-07 09:39:09.611634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c841cded694'
down_revision: Union[str, Sequence[str], None] = '7f7814b8ad67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add cafe_time_available column to menus table."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('menus')]
    
    if 'cafe_time_available' not in columns:
        # ### commands auto generated by Alembic - please adjust! ###
        with op.batch_alter_table('menus', schema=None) as batch_op:
            batch_op.add_column(sa.Column('cafe_time_available', sa.Boolean(), nullable=False, server_default='0'))
        # ### end Alembic commands ###


def downgrade() -> None:
    """Remove cafe_time_available column from menus table."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('menus')]
    
    if 'cafe_time_available' in columns:
        # ### commands auto generated by Alembic - please adjust! ###
        with op.batch_alter_table('menus', schema=None) as batch_op:
            batch_op.drop_column('cafe_time_available')
        # ### end Alembic commands ###
