"""add_unique_constraint_menu_date_title

Revision ID: b168503938a8
Revises: 6367f0a30279
Create Date: 2025-07-14 03:57:36.343220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b168503938a8'
down_revision: Union[str, Sequence[str], None] = '6367f0a30279'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.create_unique_constraint(
            'uq_menu_date_title',
            ['date', 'title']
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.drop_constraint('uq_menu_date_title', type_='unique')
    # ### end Alembic commands ###
