version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: crowdlunch
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/crowdlunch
    depends_on:
      - db
    volumes:
      - ./api:/app
    command: poetry run fastapi dev app/main.py --host 0.0.0.0

  web:
    build: ./web
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
    volumes:
      - ./web:/app
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_data:
