[build]
  base = "web"
  publish = "dist"
  command = "npm run build"

[dev]
  framework = "vite"

[[redirects]]
  from = "/api/*"
  to = "https://crowd-lunch.fly.dev/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/server-time"
  to = "https://crowd-lunch.fly.dev/server-time"
  status = 200
  force = true
