name: Deploy to Fly.io

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install FlyCTL
        run: |
          curl -L https://fly.io/install.sh | sh
          # flyctl のインストール先を PATH に追加
          echo "${HOME}/.fly/bin" >> $GITHUB_PATH

      - name: Authenticate with Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl auth token $FLY_API_TOKEN

      - name: Deploy API
        working-directory: ./api
        run: flyctl deploy --config fly.toml --remote-only
